### ISSUE TITLE
Version 0.24 checklist

### ISSUE THREAD

**Issue by nihohit** [redis-rs/redis-rs#970]
### cluster changes
- [ ] https://github.com/redis-rs/redis-rs/pull/967
- [ ] https://github.com/redis-rs/redis-rs/pull/952
### pubsub
- [ ] https://github.com/redis-rs/redis-rs/pull/633 
- [ ] https://github.com/redis-rs/redis-rs/pull/889

## nice to have
###cluster
- [ ] https://github.com/redis-rs/redis-rs/pull/965
- [ ] https://github.com/redis-rs/redis-rs/pull/938
- [ ] https://github.com/redis-rs/redis-rs/pull/834
#### cluster stability improvements:
- [ ] either https://github.com/redis-rs/redis-rs/pull/964 or https://github.com/redis-rs/redis-rs/pull/968
### pubsub
- [ ] https://github.com/redis-rs/redis-rs/pull/910
### misc
- [ ] https://github.com/redis-rs/redis-rs/pull/858
- [ ] https://github.com/redis-rs/redis-rs/pull/813 (mostly because it's a semver breaking version, so might be a good time to push this. Although I'm not sure how ready this is)

**Comment by jaymell** [comment]
Renamed since 0.24 got rushed out a bit earlier than expected.

**Comment by nihohit** [comment]
Version is ready!
